import React from 'react';
import './App.css';
import ImageList from './ImageList';

var number = 0;
var newArray =[];
class Button extends React.Component {
    constructor(props) {
      super(props);
      this.state = {
        showComponent: false,
      };
      this._onButtonClick = this._onButtonClick.bind(this);
    }

    _onButtonClick() {
      
    //   if (this.state.showComponent != null) {
    //     var images = document.getElementsByTagName('img');
    //     var l = images.length;
    //     for (var p = 0; p < l; p++) {
    //         images[0].parentNode.removeChild(images[0]);
    //         // const element = document.getElementById('image-list');
    //         // element.remove();
    //          console.log("removed")
    //     }
    // }
    // for (let i = 0; i < 6; i++) {
       // generate a number and provide to the image to generate randomly  
         number = Math.floor(Math.random() * 6);
         //print the images generated by a random number  
        // console.log(this.props.images[number]);
         newArray = [...this.props.images].sort(() => 0.5 - Math.random());

    // }
      this.setState({
        showComponent: true,
      });
      // console.log(newArray);

    }
   
    render() {
      return (
        <div>
          <button className='button' onClick={this._onButtonClick}>Button</button>
          {this.state.showComponent ?
           <ImageList images = {newArray.slice(0, 6)} />:
           //  <ImageList images={this.props.images.slice(number,  Math.floor(Math.random() * this.props.images.length))} /> :
             null
          }
        </div>
      );
    }
  }
export default Button;

// const Button = (props) => {

//     // const generateRandomImages = () => {
//         function generateRandomImages(){
//         console.log(props.images);

//         // if (document.getElementsByClassName("image-list") != null) {
//         //     var images = document.getElementsByTagName('img');
//         //     var l = images.length;
//         //     for (var p = 0; p < l; p++) {
//         //         images[0].parentNode.removeChild(images[0]);
//         //         // const element = document.getElementById('image-list');
//         //         // element.remove();
//         //          console.log("removed")
//         //     }
//         // }
//         // if (document.getElementsByClassName("image-list") != null) {
//             // for (let i = 0; i < 6; i++) {
//             //     // generate a number and provide to the image to generate randomly  
//             //     var number = Math.floor(Math.random() * props.images.length);
//             //     //print the images generated by a random number  
//             //     console.log(props.images[number]);

//             //     // var newImage = props.images[number];

//             //     var img = document.createElement("img");
//             //     img.src = props.images[number].id;
//                 // console.log(img.src);


//                 <ImageList images={props.images.slice(0, 9)} />
//                 // display the image  
//                 // document.body.appendChild(img);
//                 // document.getElementsById("span").innerHTML += '<img src="' + props.images[number].url + '" style="width:150px" />';
//                 // function getRandomInt(min, max) {
//                 //     var imn = Math.floor(Math.random() * (max - min + 1)) + min;
//                 //     console.log(props.images[imn]);
//                 //     return props.images[imn];
//                 // }
//                 // var newImage = getRandomInt(0, props.images.length - 1);

            
        
//     };

//     return (
//         <div>
//             <button className='button' onClick={generateRandomImages}>Generate</button>
//         </div>
//     );
// };

// export default Button;
