import React from 'react';
import './App.css';

const Button = (props) => {
    const generateRandomImages = () => {
      console.log(props.images);
      for (let i = 0; i < 6; i++) {
            //generate a number and provide to the image to generate randomly  
            var number = Math.floor(Math.random() * props.images.length);
            console.log(number);
            //print the images generated by a random number  
            // if(document.getElementsByClassName("image-list") != null){
            document.getElementsByClassName("image-list").innerHTML += '<img src="' + props.images[number] + '" style="width:150px" />';
            
        }
    };
  
    return (
      <div>
        <button className='button' onClick={generateRandomImages}>Generate</button>
      </div>
    );
  };

export default Button;
